<a href="https://colab.research.google.com/github/FulISun/Computer_Vision/blob/main/Keras_Simple_Linear_Regression_Exercise_Sequential.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Sequential API

In [ ]:
import tensorflow as tf

from tensorflow.keras.models import Sequential, Model
''
from tensorflow.keras.layers import Flatten, Dense, Input
from tensorflow.keras.optimizers import SGD

import numpy as np

### Data Preparation

In [ ]:
x_data = np.array( [1, 2, 3, 4, 5, 6] )
t_data = np.array( [3, 4, 5, 6, 7, 8] )

print(x_data.shape, t_data.shape)

(6,) (6,)


### Modeling: init W & b randomly

In [ ]:
model = Sequential() # 모델

model.add( Flatten(input_shape = (1,)) ) # 입력층
          
model.add( Dense(1, activation = 'linear') ) # 출력층, model.add(Dense(1))        => model.add -> W, b 초기화 되는 부분!!!

# model.add(Dense(1, input_shape = (1,), activation = 'linear')) # 위 코드 한 줄로 압축한 것

In [ ]:
# 일부러 오류 내려고 만든 것임! 실행 (X)
''' model = Sequential() # 모델

model.add( Flatten(input_shape = (2,)) ) # 입력층
model.add( Dense(2, activation = 'sigmoid') ) '''

In [ ]:
''' print(model.weights) '''
# W = 4개, b = 2개

[<tf.Variable 'dense_4/kernel:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.5677736 , -1.1336864 ],
       [ 1.0393552 , -0.00353444]], dtype=float32)>, <tf.Variable 'dense_4/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]


In [ ]:
''' model.summary() '''
# Param  6 => 가중치 4개, 바이어스 2개

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_4 (Flatten)         (None, 2)                 0         
                                                                 
 dense_4 (Dense)             (None, 2)                 6         
                                                                 
Total params: 6
Trainable params: 6
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# w, bias 각각 하나씩 필요한데
print(model.weights)

# numpy=array([[-0.75075364]] => weight
# numpy=array([0.] => bias

[<tf.Variable 'dense_1/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[-0.75075364]], dtype=float32)>, <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]


해당 데이터의 관계는 x_data + 2 = t_data이라
X*w + b 로 생각하면 w=0, b=2로 업데이트 되어야 함

### Compile: Define loss & y

In [ ]:
model.compile(optimizer = SGD(), loss = 'mse')

model.summary() # 중간 점검용 디스플레이

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 1)                 0         
                                                                 
 dense_1 (Dense)             (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


flatten (Flatten)           (None, 1) => batch자리인데 아직 batch 정해지지 않아서 None  
dense (Dense)               (None, 1)                 2  => (W, b)라서 2개

### Model Learning 

In [ ]:
# hist = model.fit(x_data, t_data, epochs = 1000) #
''' Epoch 1/1000
1/1 [==============================]          => batch는 디폴트가 32개인데, 우리 데이터는 6개니까 한번에 들여보낼 수 있으므로 1/1 '''

# hist = model.fit(x_data, t_data, epochs = 1000, batch_size = 3)
''' Epoch 1/1000
2/2 [==============================]          => 데이터 6개니까 batch 3개씩 쪼개면 2번씩 돌아야함 -> 2/2!! 즉, 한 에폭 당 2번씩 돈다는 뜻'''

hist = model.fit(x_data, t_data, epochs = 1000, batch_size = 2)
''' Epoch 1/1000
3/3 [==============================]          => 데이터 6개니까 batch 2개씩 쪼개면 3번씩 돌아야함 -> 2/2!! 즉, 한 에폭 당 3번씩 돈다는 뜻'''

# ** loss 줄어드는지 확인할 것! 

Epoch 1/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.5391e-07
Epoch 2/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.5642e-07
Epoch 3/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.5069e-07
Epoch 4/1000
3/3 [==============================] - 0s 4ms/step - loss: 1.4489e-07
Epoch 5/1000
3/3 [==============================] - 0s 2ms/step - loss: 1.5145e-07
Epoch 6/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.3858e-07
Epoch 7/1000
3/3 [==============================] - 0s 8ms/step - loss: 1.3907e-07
Epoch 8/1000
3/3 [==============================] - 0s 4ms/step - loss: 1.5284e-07
Epoch 9/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.3107e-07
Epoch 10/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.2581e-07
Epoch 11/1000
3/3 [==============================] - 0s 4ms/step - loss: 1.2577e-07
Epoch 12/1000
3/3 [==============================] - 0s 3ms/step - loss: 1.2851e-07
E

In [ ]:
print(model.weights)
# W, b가 정답에 가까워짐

[<tf.Variable 'dense_1/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[1.0000011]], dtype=float32)>, <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([1.9999957], dtype=float32)>]


### Predict

In [ ]:
test_input_data = np.array( [-3.1, 3.0, 3.5, 15.0, 20.1] )
label_data = test_input_data + 2.0

result = model.predict(test_input_data)

print(result)
print(label_data.reshape(5,1))

# 정답과 근사한 값을 예측해냄~

[[-1.1000075]
 [ 4.999999 ]
 [ 5.4999995]
 [17.000011 ]
 [22.100018 ]]
[[-1.1]
 [ 5. ]
 [ 5.5]
 [17. ]
 [22.1]]
